# Generated by Django 5.0.6 on 2024-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcontame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='sigla',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='simbolo',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
